remote_theme: pmarsceill/just-the-docs
# Set a path/url to a logo that will be displayed instead of the title
logo: "/img_Beginners/Gophernew.png"
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/
# Aux links for the upper right navigation
aux_links:
  "GopherLabs on GitHub":
    - "//github.com/sangam14/GopherLabs/"
footer_content: "Copyright &copy; 2019-2020 Sangam Biradar . Distributed by KubeDaily <a href=\"https://github.com/sangam14/GopherLabs/blob/master/LICENSE">Apache License 2.0</a>"
